#!/bin/bash
set -e

TARGET="${1:-dev}"
PROFILE="${2:-}"
SKIP_DATA=false

# Parse flags
for arg in "$@"; do
  case "$arg" in
    --skip-data) SKIP_DATA=true ;;
  esac
done

PROFILE_ARG=""
[[ -n "$PROFILE" && "$PROFILE" != --* ]] && PROFILE_ARG="-p $PROFILE"

echo "=========================================="
echo " Hospital Control Tower -- Full Setup"
echo " Target: $TARGET"
echo " Skip data: $SKIP_DATA"
echo "=========================================="
echo ""

# --- Pre-flight checks ---
echo "[Pre-flight] Checking prerequisites..."

if ! command -v databricks &> /dev/null; then
  echo "  ERROR: 'databricks' CLI not found. Install: https://docs.databricks.com/dev-tools/cli/install.html"
  exit 1
fi
echo "  Databricks CLI: OK"

if ! databricks auth describe $PROFILE_ARG &> /dev/null 2>&1; then
  echo "  WARNING: Could not verify authentication. Make sure 'databricks configure' has been run."
fi

# Read variables from variables.yml defaults, then check databricks.yml target overrides
read_var() {
  local key="$1"
  # First try variables.yml defaults
  local val
  val=$(grep -A2 "^  ${key}:" variables.yml | grep "default:" | sed 's/.*default: *"\{0,1\}\([^"]*\)"\{0,1\}/\1/' | tr -d ' ')
  # If empty, try databricks.yml target-specific overrides
  if [[ -z "$val" ]] && [[ -f databricks.yml ]]; then
    val=$(grep -A20 "^  ${TARGET}:" databricks.yml | grep "      ${key}:" | head -1 | sed 's/.*: *"\{0,1\}\([^"#]*\)"\{0,1\}.*/\1/' | tr -d ' ')
  fi
  echo "$val"
}

CATALOG=$(read_var "catalog")
SCHEMA=$(read_var "schema")
WAREHOUSE_ID=$(read_var "warehouse_id")
VECTOR_ENDPOINT=$(read_var "vector_search_endpoint")
LLM_ORCHESTRATOR=$(read_var "llm_model_orchestrator")
LLM_RAG=$(read_var "llm_model_rag")

if [[ -z "$CATALOG" ]]; then
  echo "  ERROR: 'catalog' not set in variables.yml or databricks.yml target '$TARGET'"
  exit 1
fi
if [[ -z "$SCHEMA" ]]; then
  echo "  ERROR: 'schema' not set in variables.yml or databricks.yml target '$TARGET'"
  exit 1
fi
if [[ -z "$WAREHOUSE_ID" ]]; then
  echo "  ERROR: 'warehouse_id' not set in variables.yml or databricks.yml target '$TARGET'"
  echo "         Set it in variables.yml (default) or databricks.yml (targets.$TARGET.variables.warehouse_id)"
  exit 1
fi
echo "  Catalog: $CATALOG"
echo "  Schema: $SCHEMA"
echo "  Warehouse: $WAREHOUSE_ID"
echo "  Vector Search: ${VECTOR_ENDPOINT:-<not set>}"
echo ""

# --- Step 1: Sync app.yaml from variables.yml ---
echo "[1/4] Syncing app/app.yaml from variables.yml..."

cat > app/app.yaml << APPYAML
# Databricks App Configuration (auto-generated by setup.sh)
command:
  - sh
  - -c
  - pip install -r requirements.txt && npm install && npm run build && gunicorn --bind 0.0.0.0:8000 --workers 2 --timeout 600 api_server:app

env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: "${WAREHOUSE_ID}"

  - name: CATALOG
    value: "${CATALOG}"

  - name: SCHEMA
    value: "${SCHEMA}"

  - name: VECTOR_SEARCH_ENDPOINT
    value: "${VECTOR_ENDPOINT}"

  - name: LLM_MODEL_ORCHESTRATOR
    value: "${LLM_ORCHESTRATOR:-databricks-claude-sonnet-4-5}"

  - name: LLM_MODEL_RAG
    value: "${LLM_RAG:-databricks-claude-sonnet-4-5}"

  - name: AUTONOMOUS_INTERVAL_SECONDS
    value: "3600"

  - name: AUTO_START_AUTONOMOUS
    value: "false"

  - name: MLFLOW_EXPERIMENT
    value: "/Shared/hospital-control-tower-agent"
APPYAML

echo "  app/app.yaml written"
echo ""

# --- Step 2: Deploy bundle ---
echo "[2/4] Deploying bundle..."
databricks bundle deploy -t "$TARGET" $PROFILE_ARG || { echo "FAILED: bundle deploy"; exit 1; }
echo "  Bundle deployed"
echo ""

# --- Step 3: Generate data (unless --skip-data) ---
if [[ "$SKIP_DATA" == "false" ]]; then
  echo "[3/4] Generating data..."
  databricks bundle run generate_data -t "$TARGET" $PROFILE_ARG || { echo "FAILED: generate_data"; exit 1; }
  echo "  Data generated"
else
  echo "[3/4] Skipping data generation (--skip-data)"
fi
echo ""

# --- Step 4: Run deploy.sh (permissions, vector search, diagnostics) ---
echo "[4/4] Running deploy steps (permissions, vector search, diagnostics)..."
./deploy.sh "$TARGET" "$PROFILE"

echo ""
echo "=========================================="
echo " Setup complete!"
echo ""
echo " App: ${TARGET}-hospital-control-tower"
echo " Open your Databricks workspace > Apps"
echo "=========================================="
